version: '3.8'

services:
  # Serviço para o banco de dados MySQL para Pedidos
  pedidos_db:
    image: mysql:8.0
    container_name: pedidos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_db
      MYSQL_USER: padaria
      MYSQL_PASSWORD: padaria
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Serviço para o banco de dados MySQL para Vendas
  vendas_db:
    image: mysql:8.0
    container_name: vendas_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vendas_db
      MYSQL_USER: padaria
      MYSQL_PASSWORD: padaria
    ports:
      - "3306:3306"
    volumes:
      - db_data_vendas:/var/lib/mysql

  # Serviço para o banco de dados de cliente
  cliente_db:
    image: mysql:8.0
    container_name: cliente_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cliente_db
      MYSQL_USER: padaria
      MYSQL_PASSWORD: padaria
    ports:
      - "3308:3306"
    volumes:
      - db_data_cliente:/var/lib/mysql

  # Serviço de Pedidos
  pedidos_service:
    build: ./orderService
    container_name: service_pedidos
    command: >
      sh -c "node ./src/migrations/001-create-database.js && 
             node ./src/migrations/002-create-pedido-table.js && 
             node ./src/migrations/003-create-pedido-item-table.js &&
             npm start"
    ports:
      - "3000:3000"
    depends_on:
      - pedidos_db
    environment:
      DB_HOST: pedidos_db
      DB_USER: padaria
      DB_PASSWORD: padaria
      DB_NAME: pedidos_db
    volumes:
      - ./orderService:/usr/src/app

  # Serviço de Vendas
  sell_service:
    build: ./sellService
    container_name: service_vendas
    command: >
      sh -c "npm start"
    ports:
      - "3001:3001"
    depends_on:
      - vendas_db
    environment:
      DB_HOST: vendas_db
      DB_USER: padaria
      DB_PASSWORD: padaria
      DB_NAME: vendas_db
    volumes:
      - ./sellService:/usr/src/app

  # Serviço de Cliente
  client_service:
    build: ./clientService
    container_name: service_client
    command: >
      sh -c "node ./src/migrations/001-create-database.js && 
             node ./src/migrations/002-create-table-user.js &&
             npm start"
    ports:
      - "50051:50051"
    depends_on:
      - cliente_db
    environment:
      DB_HOST: cliente_db
      DB_USER: padaria
      DB_PASSWORD: padaria
      DB_NAME: cliente_db
    volumes:
      - ./clientService:/usr/src/app

volumes:
  db_data:
  db_data_vendas:
  db_data_cliente:

networks:
  client_service-network:
    driver: bridge